apiVersion: v1
kind: Secret
metadata:
  name: mcp-registry-secrets
  namespace: mcp-registry
  labels:
    app.kubernetes.io/name: mcp-registry
    app.kubernetes.io/component: registry
stringData:
  POSTGRES_DB: "mcp-registry"
  POSTGRES_USER: "mcpregistry"
  POSTGRES_PASSWORD: "change-me"
  MCP_REGISTRY_DATABASE_URL: "postgres://mcpregistry:change-me@postgres:5432/mcp-registry"
  MCP_REGISTRY_GITHUB_CLIENT_ID: ""
  MCP_REGISTRY_GITHUB_CLIENT_SECRET: ""
  MCP_REGISTRY_JWT_PRIVATE_KEY: "813e5dd2a3fc09a69a362b9794c82391e5eaa4f1f36b6eb67db1edb429eedaa2"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: mcp-registry
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
stringData:
  POSTGRES_DB: "mcp-registry"
  POSTGRES_USER: "mcpregistry"
  POSTGRES_PASSWORD: "change-me"
